# These are supported funding model platforms

GitHub Sponsors: [username1, username2, username3, username4]  
Patreon: [patreon_username]  
Open Collective: [opencollectiveusername]  
Ko-fi: [kofi_username]  
Tidelift: [platformname/packagename]  
Community Bridge: [project_name]  
Liberapay: [liberapay_username]  
IssueHunt: [issuehunt_username]  
LFX Crowdfunding: [project_name]  
Polar: [polar_username]  
Buy Me a Coffee: [buymeacoffeeusername]  
thanks.dev: [thanksdevusername]  
Custom Sponsorship Links: [link1, link2, link3, link4]
